#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pickle



places = [{"city" :"Paris" ,"region" :"Ile-de-France","population" :"22296"},
{"city" :"Marseille" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"855393"},
{"city" :"Lyon" ,"region" :"Auvergne-Rhone-Alpes","population" :"500715"},
{"city" :"Toulouse" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"458298"},
{"city" :"Nice" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"342295"},
{"city" :"Nantes" ,"region" :"Pays de la Loire","population" :"292718"},
{"city" :"Strasbourg" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"275718"},
{"city" :"Montpellier" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"272084"},
{"city" :"Bordeaux" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"243626"},
{"city" :"Lille" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"231491"},
{"city" :"Rennes" ,"region" :"Bretagne","population" :"211373"},
{"city" :"Reims" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"182592"},
{"city" :"Le Havre" ,"region" :"Normandie","population" :"172074"},
{"city" :"Saint-Etienne" ,"region" :"Auvergne-Rhone-Alpes","population" :"172023"},
{"city" :"Toulon" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"163760"},
{"city" :"Grenoble" ,"region" :"Auvergne-Rhone-Alpes","population" :"160215"},
{"city" :"Dijon" ,"region" :"Bourgogne-Franche-Comte","population" :"153003"},
{"city" :"Nimes" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"150564"},
{"city" :"Angers" ,"region" :"Pays de la Loire","population" :"150125"},
{"city" :"Villeurbanne" ,"region" :"Auvergne-Rhone-Alpes","population" :"147192"},
{"city" :"Le Mans" ,"region" :"Pays de la Loire","population" :"144244"},
{"city" :"Saint-Denis" ,"region" :"La Reunion","population" :"142442"},
{"city" :"Aix-en-Provence" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"141545"},
{"city" :"Clermont-Ferrand" ,"region" :"Auvergne-Rhone-Alpes","population" :"141463"},
{"city" :"Brest" ,"region" :"Bretagne","population" :"139386"},
{"city" :"Limoges" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"135038"},
{"city" :"Tours" ,"region" :"Centre-Val de Loire","population" :"134803"},
{"city" :"Amiens" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"132699"},
{"city" :"Perpignan" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"120959"},
{"city" :"Metz" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"118634"},
{"city" :"Besançon" ,"region" :"Bourgogne-Franche-Comte","population" :"116952"},
{"city" :"Boulogne-Billancourt" ,"region" :"Ile-de-France","population" :"116794"},
{"city" :"Orleans" ,"region" :"Centre-Val de Loire","population" :"114375"},
{"city" :"Mulhouse" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"112063"},
{"city" :"Rouen" ,"region" :"Normandie","population" :"110755"},
{"city" :"Saint-Denis" ,"region" :"Ile-de-France","population" :"109343"},
{"city" :"Caen" ,"region" :"Normandie","population" :"107229"},
{"city" :"Argenteuil" ,"region" :"Ile-de-France","population" :"106817"},
{"city" :"Saint-Paul" ,"region" :"La Reunion","population" :"104332"},
{"city" :"Montreuil" ,"region" :"Ile-de-France","population" :"104139"},
{"city" :"Nancy" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"104072"},
{"city" :"Roubaix" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"95866"},
{"city" :"Tourcoing" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"92974"},
{"city" :"Nanterre" ,"region" :"Ile-de-France","population" :"92227"},
{"city" :"Avignon" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"90305"},
{"city" :"Vitry-sur-Seine" ,"region" :"Ile-de-France","population" :"90075"},
{"city" :"Creteil" ,"region" :"Ile-de-France","population" :"89989"},
{"city" :"Dunkerque" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"89882"},
{"city" :"Poitiers" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"87427"},
{"city" :"Asnieres-sur-Seine" ,"region" :"Ile-de-France","population" :"86020"},
{"city" :"Courbevoie" ,"region" :"Ile-de-France","population" :"85523"},
{"city" :"Versailles" ,"region" :"Ile-de-France","population" :"85272"},
{"city" :"Colombes" ,"region" :"Ile-de-France","population" :"84577"},
{"city" :"Fort-de-France" ,"region" :"Martinique","population" :"84174"},
{"city" :"Aulnay-sous-Bois" ,"region" :"Ile-de-France","population" :"82634"},
{"city" :"Saint-Pierre" ,"region" :"La Reunion","population" :"81415"},
{"city" :"Cherbourg-en-Cotentin" ,"region" :"Normandie","population" :"80878"},
{"city" :"Rueil-Malmaison" ,"region" :"Ile-de-France","population" :"79762"},
{"city" :"Pau" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"77575"},
{"city" :"Aubervilliers" ,"region" :"Ile-de-France","population" :"77452"},
{"city" :"Le Tampon" ,"region" :"La Reunion","population" :"76080"},
{"city" :"Champigny-sur-Marne" ,"region" :"Ile-de-France","population" :"75961"},
{"city" :"Antibes" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"75456"},
{"city" :"Beziers" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"74811"},
{"city" :"La Rochelle" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"74344"},
{"city" :"Saint-Maur-des-Fosses" ,"region" :"Ile-de-France","population" :"74133"},
{"city" :"Cannes" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"73325"},
{"city" :"Calais" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"72520"},
{"city" :"Saint-Nazaire" ,"region" :"Pays de la Loire","population" :"68513"},
{"city" :"Merignac" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"68386"},
{"city" :"Drancy" ,"region" :"Ile-de-France","population" :"68241"},
{"city" :"Colmar" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"67956"},
{"city" :"Ajaccio" ,"region" :"Corse","population" :"67507"},
{"city" :"Bourges" ,"region" :"Centre-Val de Loire","population" :"67189"},
{"city" :"Issy-les-Moulineaux" ,"region" :"Ile-de-France","population" :"65662"},
{"city" :"Levallois-Perret" ,"region" :"Ile-de-France","population" :"65264"},
{"city" :"La Seyne-sur-Mer" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"64523"},
{"city" :"Quimper" ,"region" :"Bretagne","population" :"63532"},
{"city" :"Noisy-le-Grand" ,"region" :"Ile-de-France","population" :"62834"},
{"city" :"Villeneuve-d'Ascq" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"62616"},
{"city" :"Neuilly-sur-Seine" ,"region" :"Ile-de-France","population" :"62346"},
{"city" :"Valence" ,"region" :"Auvergne-Rhone-Alpes","population" :"61767"},
{"city" :"Antony" ,"region" :"Ile-de-France","population" :"61727"},
{"city" :"Cergy" ,"region" :"Ile-de-France","population" :"61708"},
{"city" :"Venissieux" ,"region" :"Auvergne-Rhone-Alpes","population" :"61636"},
{"city" :"Pessac" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"60763"},
{"city" :"Troyes" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"59671"},
{"city" :"Clichy" ,"region" :"Ile-de-France","population" :"59255"},
{"city" :"Ivry-sur-Seine" ,"region" :"Ile-de-France","population" :"58933"},
{"city" :"Chambery" ,"region" :"Auvergne-Rhone-Alpes","population" :"58653"},
{"city" :"Lorient" ,"region" :"Bretagne","population" :"57961"},
{"city" :"Les Abymes" ,"region" :"Guadeloupe","population" :"57960"},
{"city" :"Montauban" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"57921"},
{"city" :"Sarcelles" ,"region" :"Ile-de-France","population" :"57533"},
{"city" :"Niort" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"57393"},
{"city" :"Mamoudzou" ,"region" :"Mayotte","population" :"572"},
{"city" :"Villejuif" ,"region" :"Ile-de-France","population" :"57184"},
{"city" :"Saint-Andre" ,"region" :"La Reunion","population" :"56156"},
{"city" :"Hyeres" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"55713"},
{"city" :"Saint-Quentin" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"55698"},
{"city" :"Beauvais" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"55252"},
{"city" :"Epinay-sur-Seine" ,"region" :"Ile-de-France","population" :"54857"},
{"city" :"Cayenne" ,"region" :"Guyane","population" :"54709"},
{"city" :"Maisons-Alfort" ,"region" :"Ile-de-France","population" :"54470"},
{"city" :"Cholet" ,"region" :"Pays de la Loire","population" :"53890"},
{"city" :"Meaux" ,"region" :"Ile-de-France","population" :"53766"},
{"city" :"Chelles" ,"region" :"Ile-de-France","population" :"53569"},
{"city" :"Pantin" ,"region" :"Ile-de-France","population" :"53471"},
{"city" :"Evry" ,"region" :"Ile-de-France","population" :"53237"},
{"city" :"Fontenay-sous-Bois" ,"region" :"Ile-de-France","population" :"53124"},
{"city" :"Frejus" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"53039"},
{"city" :"Vannes" ,"region" :"Bretagne","population" :"53032"},
{"city" :"Bondy" ,"region" :"Ile-de-France","population" :"52865"},
{"city" :"Narbonne" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"52802"},
{"city" :"Le Blanc-Mesnil" ,"region" :"Ile-de-France","population" :"52797"},
{"city" :"La Roche-sur-Yon" ,"region" :"Pays de la Loire","population" :"52732"},
{"city" :"Saint-Louis" ,"region" :"La Reunion","population" :"52656"},
{"city" :"Arles" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"52566"},
{"city" :"Clamart" ,"region" :"Ile-de-France","population" :"52203"},
{"city" :"Annecy" ,"region" :"Auvergne-Rhone-Alpes","population" :"52029"},
{"city" :"Sartrouville" ,"region" :"Ile-de-France","population" :"51599"},
{"city" :"Grasse" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"50916"},
{"city" :"Laval" ,"region" :"Pays de la Loire","population" :"50479"},
{"city" :"Belfort" ,"region" :"Bourgogne-Franche-Comte","population" :"50196"},
{"city" :"Bobigny" ,"region" :"Ile-de-France","population" :"49802"},
{"city" :"Evreux" ,"region" :"Normandie","population" :"49722"},
{"city" :"Vincennes" ,"region" :"Ile-de-France","population" :"49695"},
{"city" :"Montrouge" ,"region" :"Ile-de-France","population" :"49656"},
{"city" :"Sevran" ,"region" :"Ile-de-France","population" :"49465"},
{"city" :"Albi" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"49342"},
{"city" :"Charleville-Mezieres" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"48991"},
{"city" :"Suresnes" ,"region" :"Ile-de-France","population" :"48066"},
{"city" :"Martigues" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"47904"},
{"city" :"Corbeil-Essonnes" ,"region" :"Ile-de-France","population" :"47632"},
{"city" :"Saint-Ouen" ,"region" :"Ile-de-France","population" :"47534"},
{"city" :"Bayonne" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"47492"},
{"city" :"Cagnes-sur-Mer" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"46940"},
{"city" :"Brive-la-Gaillarde" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"46794"},
{"city" :"Carcassonne" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"46724"},
{"city" :"Massy" ,"region" :"Ile-de-France","population" :"45902"},
{"city" :"Blois" ,"region" :"Centre-Val de Loire","population" :"45539"},
{"city" :"Saint-Brieuc" ,"region" :"Bretagne","population" :"45331"},
{"city" :"Aubagne" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"45303"},
{"city" :"Châteauroux" ,"region" :"Centre-Val de Loire","population" :"45209"},
{"city" :"Chalon-sur-Saone" ,"region" :"Bourgogne-Franche-Comte","population" :"45166"},
{"city" :"Mantes-la-Jolie" ,"region" :"Ile-de-France","population" :"45052"},
{"city" :"Meudon" ,"region" :"Ile-de-France","population" :"45043"},
{"city" :"Saint-Malo" ,"region" :"Bretagne","population" :"44919"},
{"city" :"Châlons-en-Champagne" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"44899"},
{"city" :"Alfortville" ,"region" :"Ile-de-France","population" :"44818"},
{"city" :"Sete" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"44270"},
{"city" :"Salon-de-Provence" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"44263"},
{"city" :"Vaulx-en-Velin" ,"region" :"Auvergne-Rhone-Alpes","population" :"44087"},
{"city" :"Puteaux" ,"region" :"Ile-de-France","population" :"43891"},
{"city" :"Rosny-sous-Bois" ,"region" :"Ile-de-France","population" :"43802"},
{"city" :"Saint-Herblain" ,"region" :"Pays de la Loire","population" :"43784"},
{"city" :"Gennevilliers" ,"region" :"Ile-de-France","population" :"43219"},
{"city" :"Le Cannet" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"43187"},
{"city" :"Livry-Gargan" ,"region" :"Ile-de-France","population" :"43099"},
{"city" :"Saint-Priest" ,"region" :"Auvergne-Rhone-Alpes","population" :"42950"},
{"city" :"Istres" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"42937"},
{"city" :"Valenciennes" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"42851"},
{"city" :"Choisy-le-Roi" ,"region" :"Ile-de-France","population" :"42769"},
{"city" :"Caluire-et-Cuire" ,"region" :"Auvergne-Rhone-Alpes","population" :"42581"},
{"city" :"Boulogne-sur-Mer" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"42537"},
{"city" :"Bastia" ,"region" :"Corse","population" :"42254"},
{"city" :"Angouleme" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"41970"},
{"city" :"Garges-les-Gonesse" ,"region" :"Ile-de-France","population" :"41782"},
{"city" :"Castres" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"41636"},
{"city" :"Thionville" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"41627"},
{"city" :"Wattrelos" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"41552"},
{"city" :"Talence" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"41517"},
{"city" :"Saint-Laurent-du-Maroni" ,"region" :"Guyane","population" :"41515"},
{"city" :"Douai" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"41189"},
{"city" :"Noisy-le-Sec" ,"region" :"Ile-de-France","population" :"41125"},
{"city" :"Tarbes" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"41062"},
{"city" :"Arras" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"40830"},
{"city" :"Ales" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"40771"},
{"city" :"La Courneuve" ,"region" :"Ile-de-France","population" :"40678"},
{"city" :"Bourg-en-Bresse" ,"region" :"Auvergne-Rhone-Alpes","population" :"40490"},
{"city" :"Compiegne" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"40430"},
{"city" :"Gap" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"40255"},
{"city" :"Melun" ,"region" :"Ile-de-France","population" :"40066"},
{"city" :"Le Lamentin" ,"region" :"Martinique","population" :"40040"},
{"city" :"Reze" ,"region" :"Pays de la Loire","population" :"39568"},
{"city" :"Saint-Germain-en-Laye" ,"region" :"Ile-de-France","population" :"39547"},
{"city" :"Marcq-en-Barœul" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"39392"},
{"city" :"Gagny" ,"region" :"Ile-de-France","population" :"39276"},
{"city" :"Anglet" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"39184"},
{"city" :"Draguignan" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"39174"},
{"city" :"Chartres" ,"region" :"Centre-Val de Loire","population" :"38840"},
{"city" :"Bron" ,"region" :"Auvergne-Rhone-Alpes","population" :"38746"},
{"city" :"Bagneux" ,"region" :"Ile-de-France","population" :"38520"},
{"city" :"Colomiers" ,"region" :"Languedoc-Roussillon-Midi-Pyrenees","population" :"38302"},
{"city" :"Saint-Martin-d'Heres" ,"region" :"Auvergne-Rhone-Alpes","population" :"38019"},
{"city" :"Pontault-Combault" ,"region" :"Ile-de-France","population" :"37847"},
{"city" :"Montluçon" ,"region" :"Auvergne-Rhone-Alpes","population" :"37839"},
{"city" :"Joue-les-Tours" ,"region" :"Centre-Val de Loire","population" :"37707"},
{"city" :"Saint-Joseph" ,"region" :"La Reunion","population" :"37550"},
{"city" :"Poissy" ,"region" :"Ile-de-France","population" :"37461"},
{"city" :"Savigny-sur-Orge" ,"region" :"Ile-de-France","population" :"37206"},
{"city" :"Montelimar" ,"region" :"Auvergne-Rhone-Alpes","population" :"36643"},
{"city" :"Villefranche-sur-Saone" ,"region" :"Auvergne-Rhone-Alpes","population" :"36531"},
{"city" :"Stains" ,"region" :"Ile-de-France","population" :"36365"},
{"city" :"Saint-Benoit" ,"region" :"La Reunion","population" :"36131"},
{"city" :"Bagnolet" ,"region" :"Ile-de-France","population" :"35984"},
{"city" :"Châtillon" ,"region" :"Ile-de-France","population" :"35964"},
{"city" :"Le Port" ,"region" :"La Reunion","population" :"35881"},
{"city" :"Sainte-Genevieve-des-Bois" ,"region" :"Ile-de-France","population" :"35868"},
{"city" :"Saint-Martin", "population" : "36594"},
{"city" :"Echirolles" ,"region" :"Auvergne-Rhone-Alpes","population" :"35684"},
{"city" :"Roanne" ,"region" :"Auvergne-Rhone-Alpes","population" :"35507"},
{"city" :"Villepinte" ,"region" :"Ile-de-France","population" :"35329"},
{"city" :"Saint-Chamond" ,"region" :"Auvergne-Rhone-Alpes","population" :"35308"},
{"city" :"Conflans-Sainte-Honorine" ,"region" :"Ile-de-France","population" :"35213"},
{"city" :"Auxerre" ,"region" :"Bourgogne-Franche-Comte","population" :"34869"},
{"city" :"Nevers" ,"region" :"Bourgogne-Franche-Comte","population" :"34841"},
{"city" :"Neuilly-sur-Marne" ,"region" :"Ile-de-France","population" :"34756"},
{"city" :"La Ciotat" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"34655"},
{"city" :"Tremblay-en-France" ,"region" :"Ile-de-France","population" :"34614"},
{"city" :"Thonon-les-Bains" ,"region" :"Auvergne-Rhone-Alpes","population" :"34610"},
{"city" :"Vitrolles" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"34493"},
{"city" :"Haguenau" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"34419"},
{"city" :"Six-Fours-les-Plages" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"34387"},
{"city" :"Agen" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"34344"},
{"city" :"Creil" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"34262"},
{"city" :"Annemasse" ,"region" :"Auvergne-Rhone-Alpes","population" :"34261"},
{"city" :"Saint-Raphaël" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"34005"},
{"city" :"Marignane" ,"region" :"Provence-Alpes-Cote d'Azur","population" :"33986"},
{"city" :"Romans-sur-Isere" ,"region" :"Auvergne-Rhone-Alpes","population" :"33632"},
{"city" :"Montigny-le-Bretonneux" ,"region" :"Ile-de-France","population" :"33625"},
{"city" :"Le Perreux-sur-Marne" ,"region" :"Ile-de-France","population" :"33480"},
{"city" :"Franconville" ,"region" :"Ile-de-France","population" :"33375"},
{"city" :"Mâcon" ,"region" :"Bourgogne-Franche-Comte","population" :"33350"},
{"city" :"Saint-Leu" ,"region" :"La Reunion","population" :"33154"},
{"city" :"Cambrai" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"32852"},
{"city" :"Châtenay-Malabry" ,"region" :"Ile-de-France","population" :"32623"},
{"city" :"Sainte-Marie" ,"region" :"La Reunion","population" :"32605"},
{"city" :"Villeneuve-Saint-Georges" ,"region" :"Ile-de-France","population" :"32575"},
{"city" :"Houilles" ,"region" :"Ile-de-France","population" :"32287"},
{"city" :"Epinal" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"32188"},
{"city" :"Lens" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"31647"},
{"city" :"Lievin" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"31517"},
{"city" :"Les Mureaux" ,"region" :"Ile-de-France","population" :"31487"},
{"city" :"Schiltigheim" ,"region" :"Alsace-Champagne-Ardenne-Lorraine","population" :"31450"},
{"city" :"La Possession" ,"region" :"La Reunion","population" :"31439"},
{"city" :"Meyzieu" ,"region" :"Auvergne-Rhone-Alpes","population" :"31438"},
{"city" :"Dreux" ,"region" :"Centre-Val de Loire","population" :"31373"},
{"city" :"Nogent-sur-Marne" ,"region" :"Ile-de-France","population" :"31367"},
{"city" :"Plaisir" ,"region" :"Ile-de-France","population" :"31342"},
{"city" :"Mont-de-Marsan" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"31334"},
{"city" :"Palaiseau" ,"region" :"Ile-de-France","population" :"31264"},
{"city" :"Châtellerault" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"31262"},
{"city" :"Goussainville" ,"region" :"Ile-de-France","population" :"31212"},
{"city" :"L'Haÿ-les-Roses" ,"region" :"Ile-de-France","population" :"31201"},
{"city" :"Viry-Châtillon" ,"region" :"Ile-de-France","population" :"31132"},
{"city" :"Vigneux-sur-Seine" ,"region" :"Ile-de-France","population" :"31126"},
{"city" :"Trappes" ,"region" :"Ile-de-France","population" :"30979"},
{"city" :"Chatou" ,"region" :"Ile-de-France","population" :"30809"},
{"city" :"Clichy-sous-Bois" ,"region" :"Ile-de-France","population" :"30725"},
{"city" :"Villenave-d'Ornon" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"30663"},
{"city" :"Rillieux-la-Pape" ,"region" :"Auvergne-Rhone-Alpes","population" :"30645"},
{"city" :"Maubeuge" ,"region" :"Nord-Pas-de-Calais-Picardie","population" :"30567"},
{"city" :"Charenton-le-Pont" ,"region" :"Ile-de-France","population" :"30408"},
{"city" :"Malakoff" ,"region" :"Ile-de-France","population" :"30303"},
{"city" :"Matoury" ,"region" :"Guyane","population" :"30244"},
{"city" :"Dieppe" ,"region" :"Normandie","population" :"30214"},
{"city" :"Athis-Mons" ,"region" :"Ile-de-France","population" :"30094"},
{"city" :"Savigny-le-Temple" ,"region" :"Ile-de-France","population" :"30068"},
{"city" :"Perigueux" ,"region" :"Aquitaine-Limousin-Poitou-Charentes","population" :"30036"},
{"city" :"Baie-Mahault" ,"region" :"Guadeloupe","population" :"30015"}]


def writeIt() :
	with open('cityData', 'wb') as handle:
		pickle.dump(places, handle)

writeIt()

#with open("cities","wb") as output : 
#	output.write("["+"City"+",RentSalaryRation"+",JavaJobs"+",State"+",Population],\n")
#	for place in places :
#		if 'rentSalaryRatio' in place and 'javaJobs' in place : 
#			output.write("['"+place['city']+"',"+str(place['rentSalaryRatio'])+","+str(place['javaJobs'])+",'"+place['state'].replace("'","")+"',"+str(place['population'].replace(",",""))+"],\n")


